### PR TITLE
Add CMake configuration to run Doxygen by calling daq_create_document…

### PR DESCRIPTION
**Pull request by eflumerf**
…ation() in a package CMakeLists.txt file

Still needs testing of dependencies and excludes, with dependency testing including dependencies in both UPS and source directory.

### CODE REVIEW

**Comment by eflumerf** [comment]
I tested in-source dependencies by having dataformats and dfmessages in my sourcecode directory, and adding daq_create_documentation() to dataformats/CMakeLists.txt and daq_create_documentations(DEPENDS dataformats) to dfmessages/CMakeLists.txt. The generated dfmessages HTML does correctly reference the dataformats HTML pages.

**Comment by alessandrothea** [comment]
Thanks a lot Eric, I'll have look into this next week. Just a couple of preliminary questions:
- What dependencies are required? Doxygen and Latex? Are they available as UPS?
- Do you envisage doxygen docs to be build by default or through a dedicated target?

**Comment by eflumerf** [comment]
The current configuration uses FindDoxygen and FindLatex. If Doxygen is not available (system installed), then the module does nothing. Likewise, if Latex is not found, then the PDF documentation is not generated. I'm not sure about packaging Latex as it tends to be full of little pieces that get regular updates, but we can discuss this.

Right now, it's configured to always run if ${PACKAGE_NAME}.tag is not found in the build/doc directory. It does not automatically re-run when source files change. I was thinking we could perhaps guard the target with a CMake variable which could be set via something like `dbt-build.sh --docs`.

**Comment by dingp** [comment]
@alessandrothea The discussion seems to be stalled. Could this get some momentum so that the feature can be included in `dunedaq-v2.10.0`?

**Comment by dingp** [comment]
Closing this PR. New issue will be opened in `docs` repo to discuss the solution regarding doxygen.

**Pull request closed without merging**
