### PR TITLE
Templates for package creation moved to config/templates

### PR DESCRIPTION
**Pull request by alessandrothea**
See #79

### CODE REVIEW

**Comment by jcfreeman2** [comment]
Two quick things:
1) If I try `create_dunedaq_package johnspackage --daq-module JohnModule --test-app try_to_test_stuff` I get 
```
Traceback (most recent call last):
  File "/nfs/sw/work_dirs/jcfree/daqbuild_mar9/install/daq-cmake/bin/create_dunedaq_package", line 107, in <module>
    TEMPLATEDIR = (pathlib.Path(os.environ['DAQ_CMAKE_SHARE']) + "config" + "templates").resolve()
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'
```
2) I see a lot of files got moved from `scripts/` to `config/`; let's check to make sure the documentation isn't "broken" by this change

**Comment by alessandrothea** [comment]
Thanks @jcfreeman2. I've fixed the (stupid) bug I left in the code.
Now it should work.
I would be surprised if documentation relies on template files, but worth checking. A quick pass hasn't revealed anything in docs.

**Comment by alessandrothea** [comment]
Instead, do you want to address here my comment about the template file names being a bit cryptic (`renameme*`, `RenameMe*`) or in a separate one?

**Comment by jcfreeman2** [comment]
I went through the https://dune-daq-sw.readthedocs.io/en/latest/packages/daq-cmake/#the-create_dunedaq_package-script instructions and things continued to work after the refactor; merged. If there's a better choice for a template file name than `renameme` then let's do that in a separate PR.

**Pull request merged**
