### PR TITLE
Johnfreeman/daq deliverables issue26 create package

### PR DESCRIPTION
**Pull request by jcfreeman2**

### CODE REVIEW

**Comment by jcfreeman2** [comment]
Testing this PR translates to testing the `dunedaq_create_package.py` script and its accompanying documentation. In your development area, you'll want to clone daq-cmake on this feature branch and build it. From the base of your development area:
```
cd sourcecode
git clone https://github.com/DUNE-DAQ/daq-cmake --branch johnfreeman/daq-deliverables_issue26_create_package
cd ..
dbt-build
dbt-workarea-env
```
At this point you'll have `create_dunedaq_package.py` available. To learn about how to use it, go to the daq-cmake documentation on this PR's feature branch, https://github.com/DUNE-DAQ/daq-cmake/tree/johnfreeman/daq-deliverables_issue26_create_package#readme . 

Also, please note: since `create_dunedaq_package.py` assumes the existence of an empty repo, for testing purposes you're _required_ to provide`skeleton` as the name of the repo for the script. This refers to an empty repo in my own github account which I created so this script could be tested. When we merge, of course, I'll switch the script over to expecting an empty repo in the DUNE-DAQ organization.

**Review by glehmannmiotto — COMMENTED** [review]
I got stuck pretty quickly because the script assumes that there is already a git repo and doesn't even ask me where it should be:
ERROR: [Fri Sep 2 15:23:39 CEST 2022] [/nfs/home/glehmann/NT22-08-25/install/daq-cmake/bin/create_dunedaq_package.py:102]: 
git was either unable to find a https://github.com/jcfreeman2/modulestest/ repository
or it already existed in /nfs/home/glehmann/NT22-08-25/sourcecode
and couldn't be overwritten

I don't think it's a good idea to tie the package generation to git

**Comment by jcfreeman2** [comment]
Given Giovanna's comment here + a discussion we had on Slack, I've made the following changes:
* `create_dunedaq_package.py` no longer requires the existence of a git repo on Slack. In general, its coupling to git is now essentially zero - e.g. I got rid of a feature whereby after the code was generated a local git commit of the code was made
* I got rid of all the transition functions except for `do_conf`. In the jsonnet code for a given DAQModule a very simple record is defined for educational purposes, and `do_conf` extracts a value from it. 
* In a couple of places, I've added comments for developers which should help them contextualize what's going on
* I corrected a previous oversight of mine so that now when `--python-bindings` is passed as an argument, an `__init__.py` file is installed so `import <packagename>` will work in Python 
* I've also updated the documentation, https://github.com/DUNE-DAQ/daq-cmake/tree/johnfreeman/daq-deliverables_issue26_create_package#readme, where appropriate.

**Comment by glehmannmiotto** [comment]
I like this new version of the create_dunedaq_package very much. If you want to improve it further you may also add an example metrics in the info jsonnet, used in the get_info() method.

**Comment by jcfreeman2** [comment]
Good idea, I can do that in the next day or so.

**Comment by glehmannmiotto** [comment]
One more thing we could explore is creating a demo configuration generation script, creating a DAQ application containing a variable number of instances of modules of the package, without interconnection (we cannot guess anything about the logic of the modules and how they relate to each other). this corresponds to having a script that resembles listrev_gen or wibmod_gen, (that need to be updated to the new daqconf using a config file!), and the corresponding python module, similar to listrev_app_gen.py (or wibmod_app_gen.py).

**Comment by glehmannmiotto** [comment]
get_info example also looks good.

**Comment by jcfreeman2** [comment]
This PR is ready to be re-reviewed. The state of things is as follows:
1) I renamed the script `create_dunedaq_package`, dropping the `.py`; this is more consistent with how we name Python scripts elsewhere in the DUNE DAQ suite. 
2) I've added a `--config-generation` option to `create_dunedaq_package`, which will produce a `<your package>_gen` script analogous to what you find in `listrev` or `wibapp`
3) I've updated the documentation to reflect the new script name and new option, as well as made opportunistic changes (e.g., changing a reference from UPS to Spack in the schema section at the bottom). See https://github.com/DUNE-DAQ/daq-cmake/tree/johnfreeman/daq-deliverables_issue26_create_package#readme

**Comment by glehmannmiotto** [comment]
I tried the configuration generation using the example json config file and get the following error:
[11:52:11] Parsing config json file sourcecode/thenewpackage/scripts/thenewpackage_example_config.json                                                                                                                                                                                                                                                        config_file.py:41
[11:52:12]                                                                                                                                                                                                                                                                                                                                                 thenewpackage_gen:42
           Individual configuration records before any command line overrides:                                                                                                                                                                                                                                                                                                 
           boot configuration object: {'base_command_port': 4444, 'disable_trace': False, 'opmon_impl': 'local', 'ers_impl': 'local', 'pocket_url': '127.0.0.1', 'image': '', 'use_k8s': False, 'op_env': 'swtest', 'data_request_timeout_ms': 1000}                                                                                                       thenewpackage_gen:46
           thenewpackage configuration object: {'some_configured_value': 27182, 'num_afirstmodules': 2}                                                                                                                                                                                                                                                    thenewpackage_gen:49
                                                                                                                                                                                                                                                                                                                                                           thenewpackage_gen:51
           Individual configuration records after any command line overrides:                                                                                                                                                                                                                                                                                                  
           boot configuration object: {'base_command_port': 4444, 'disable_trace': False, 'opmon_impl': 'local', 'ers_impl': 'local', 'pocket_url': '127.0.0.1', 'image': '', 'use_k8s': False, 'op_env': 'swtest', 'data_request_timeout_ms': 1000}                                                                                                       thenewpackage_gen:52
           thenewpackage configuration object: {'some_configured_value': 27182, 'num_afirstmodules': 2}                                                                                                                                                                                                                                                    thenewpackage_gen:53
           Loading thenewpackageapp config generator                                                                                                                                                                                                                                                                                                       thenewpackage_gen:55
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│                                                                                                  │
│ /nfs/home/glehmann/N22-09-15/install/thenewpackage/bin/thenewpackage_gen:89 in <module>          │
│                                                                                                  │
│   86                                                                                             │
│   87 if __name__ == "__main__":                                                                  │
│   88 │   try:                                                                                    │
│ ❱ 89 │   │   cli(show_default=True, standalone_mode=True)                                        │
│   90 │   except Exception:                                                                       │
│   91 │   │   console.print_exception()                                                           │
│   92                                                                                             │
│ /nfs/home/glehmann/N22-09-15/dbt-pyvenv/lib/python3.8/site-packages/click/core.py:1130 in        │
│ __call__                                                                                         │
│                                                                                                  │
│   1127 │                                                                                         │
│   1128 │   def __call__(self, *args: t.Any, **kwargs: t.Any) -> t.Any:                           │
│   1129 │   │   """Alias for :meth:`main`."""                                                     │
│ ❱ 1130 │   │   return self.main(*args, **kwargs)                                                 │
│   1131                                                                                           │
│   1132                                                                                           │
│   1133 class Command(BaseCommand):                                                               │
│                                                                                                  │
│ /nfs/home/glehmann/N22-09-15/dbt-pyvenv/lib/python3.8/site-packages/click/core.py:1055 in main   │
│                                                                                                  │
│   1052 │   │   try:                                                                              │
│   1053 │   │   │   try:                                                                          │
│   1054 │   │   │   │   with self.make_context(prog_name, args, **extra) as ctx:                  │
│ ❱ 1055 │   │   │   │   │   rv = self.invoke(ctx)                                                 │
│   1056 │   │   │   │   │   if not standalone_mode:                                               │
│   1057 │   │   │   │   │   │   return rv                                                         │
│   1058 │   │   │   │   │   # it's not safe to `ctx.exit(rv)` here!                               │
│                                                                                                  │
│ /nfs/home/glehmann/N22-09-15/dbt-pyvenv/lib/python3.8/site-packages/click/core.py:1404 in invoke │
│                                                                                                  │
│   1401 │   │   │   echo(style(message, fg="red"), err=True)                                      │
│   1402 │   │                                                                                     │
│   1403 │   │   if self.callback is not None:                                                     │
│ ❱ 1404 │   │   │   return ctx.invoke(self.callback, **ctx.params)                                │
│   1405 │                                                                                         │
│   1406 │   def shell_complete(self, ctx: Context, incomplete: str) -> t.List["CompletionItem"]:  │
│   1407 │   │   """Return a list of completions for the incomplete value. Looks                   │
│                                                                                                  │
│ /nfs/home/glehmann/N22-09-15/dbt-pyvenv/lib/python3.8/site-packages/click/core.py:760 in invoke  │
│                                                                                                  │
│    757 │   │                                                                                     │
│    758 │   │   with augment_usage_errors(__self):                                                │
│    759 │   │   │   with ctx:                                                                     │
│ ❱  760 │   │   │   │   return __callback(*args, **kwargs)                                        │
│    761 │                                                                                         │
│    762 │   def forward(                                                                          │
│    763 │   │   __self, __cmd: "Command", *args: t.Any, **kwargs: t.Any  # noqa: B902             │
│                                                                                                  │
│ /nfs/home/glehmann/N22-09-15/install/thenewpackage/bin/thenewpackage_gen:62 in cli               │
│                                                                                                  │
│   59 │                                                                                           │
│   60 │   the_system.apps["thenewpackage_app"] = thenewpackageapp_gen.get_thenewpackage_app(      │
│   61 │   │   nickname = "the_solo_app",                                                          │
│ ❱ 62 │   num_afirstmodules = skeleton.num_afirstmodules,                                         │
│   63 │   some_configured_value = thenewpackage.some_configured_value                             │
│   64 │   )                                                                                       │
│   65                                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
NameError: name 'skeleton' is not defined

**Comment by glehmannmiotto** [comment]
I also find the instructions a bit convoluted now. 
We should give trivial operational instructions on how to use the utility. You provide an example command line option already (but then you introduce the toy library that is a confusing). I would expect to see an example for generating the package, compiling it, generating the configuration, running it.

**Comment by jcfreeman2** [comment]
Fixed the line that caused the crash, and updated the documentation.

**Review by glehmannmiotto — APPROVED** [review]
LGTM!

**Pull request merged**
